config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: "pages#dashboard"
  resources :cars do
    resources :bookings
    post 'bookings/new', to: 'bookings#new', as: :send_booking
  end
  resources :bookings do
    resources :reviews
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_one :review
  validates :renting_time, presence: true
  belongs_to :user
  belongs_to :car
  validates :user_id, uniqueness: { scope: :car_id }
  validates :status, inclusion: { in: ['pending', 'accepted', 'declined'] }
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  validates :brand, presence: true
  validates :milage, presence: true
  validates :car_model, presence: true
  validates :price_per_hour, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  include PgSearch::Model
  pg_search_scope :search_car,
    against: [:brand, :price_per_hour, :car_model, :transmission, :year],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :content, presence: true
  validates :content, length: { maximum: 60 }
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cars
  has_many :bookings
  has_many :bookings, through: :cars
  has_many :reviews, through: :bookings
  # validates :role, inclusion: { in: ['owner', 'customer'] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!, only: [:new, :create, :destroy, :edit, :update]
  after_action :verify_authorized, only: [:edit, :update, :destroy], unless: :skip_pundit?
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  rescue_from Pundit::AuthorizationNotPerformedError, with: :user_success
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def user_success
    flash[:notice] = "Success"
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @start_time = params["booking"]["starts_at"]
    @end_time = params["booking"]["ends_at"]
    @start_time_hours = DateTime.parse(params["booking"]["starts_at"]).strftime('%s').to_f / 3600
    @end_time_hours = DateTime.parse(params["booking"]["ends_at"]).strftime('%s').to_f / 3600
    @car = Car.find(params[:car_id])
    @result = ((@end_time_hours - @start_time_hours) * @car.price_per_hour).round
    @marker = { lat: @car.latitude, lng: @car.longitude, infoWindow: render_to_string(partial: "../views/cars/info_window", locals: { car: @car }), image_url: helpers.asset_url('markernew.png') }
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @car = Car.find(params[:car_id])
    @booking.car = @car
    @booking.user_id = current_user.id
    @booking.status = "accepted"
    @booking.save!
    redirect_to car_path(@car)
  end

  def index
  end

  private

  def booking_params
    params.permit(:renting_time, :starts_at, :ends_at)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:edit, :update, :show, :destroy]

  def new
    @car = Car.new
  end
  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save!
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_path
    authorize @car
  end

  def edit
    @car
    authorize @car
  end

  def update
    @car.update(car_params)
    redirect_to @car
  end

  def index
    @cars = Car.geocoded

    if params[:query].present?
      @cars = Car.search_car(params[:query])
    end

    @markers = @cars.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { car: car }),
        image_url: helpers.asset_url('markernew.png')
      }
    end
  end

  def show
    @marker = { lat: @car.latitude, lng: @car.longitude, infoWindow: render_to_string(partial: "info_window", locals: { car: @car }), image_url: helpers.asset_url('markernew.png') }
    @bookings = Booking.all.select { |book| book.car_id == @car.id }
    usercars = Car.all.select { |car| car.user_id == @car.user.id }
    usercarsids = usercars.map { |car| car.id }
    @usersbookings = Booking.all.select { |book| usercarsids.include? book.car_id }
    @lasumabook = 0
    @lamediabook = 0
    @lasumauser = 0
    @lamediauser = 0
    @numreviewbook = 0
    @numreviewuser = 0
    unless @bookings.length == 0
      @bookings.each { |book| @lasumabook += book.review.rating if book.review }
      @bookings.each { |book| @numreviewbook += 1 if book.review }
      @numreviewbook.zero? ?  @lamediabook = 0 : @lamediabook = (@lasumabook / @numreviewbook).round
    end
    unless @usersbookings.length == 0
      @usersbookings.each { |book| @lasumauser += book.review.rating if book.review }
      @usersbookings.each { |book| @numreviewuser += 1 if book.review }
      @numreviewuser.zero? ? @lamediauser = 0 : @lamediauser = (@lasumauser / @numreviewuser).round
    end
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:brand, :price_per_hour, :milage, :photo, :user_id, :plate_number, :car_model, :location)
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @cars = Car.all
  end

  def dashboard
    @user = current_user
    @cars = Car.all.select { |car| car.user_id == @user.id }
    @rentals = Booking.all.select { |book| book.user_id == @user.id }
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_booking, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to car_path(@booking.car_id)
    else
      render :new
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content, :booking_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container text-center mt-5 main-cnt">
  <div class="top-info-cont">
    <img src='<%= @car.photo %>' class="car-image" alt="">
  </div>
  <h1 class="mt-4 mb-4"><%= @car.brand.upcase %> <%= @car.year %></h1>
  <%= simple_form_for [@car, @booking] do |f| %>
  <div class="mapcards">
    <div class="mapcard p-2 mb-3">
        <div class="text-left">
        <p class="m-0"><strong>PICK UP ADDRESS</strong></p>
        <p class="m-0"><%= @car.location %></p>
        </div>
    </div>
    <div class="mapcard p-2 mb-3">
        <div class="text-left">
        <p class="m-0"><strong>PLATE NUMBER</strong></p>
        <p class="m-0"><%= @car.plate_number %></p>
        </div>
    </div>
    <div class="mapcard p-2 mb-3">
        <div class="text-left">
        <p class="m-0"><strong>ACCESSORIES</strong></p>
        <p class="m-0"><%= @car.accessories %></p>
        </div>
    </div>
    <div class="mapcard p-2 mb-3">
        <div class="text-left">
        <p class="m-0"><strong>SEATS</strong></p>
        <p class="m-0"><%= @car.seats %></p>
        </div>
    </div>
    <div class="mapcard p-2 mb-3">
        <div class="text-left">
        <p class="m-0"><strong>OWNER</strong></p>
        <p class="m-0"><%= @car.user.full_name %></p>
        </div>
    </div>
  </div>
  <div class="text-center m-3">
    <h3>Pick up location: </h3>
      <div
    id="map"
    class=""
    style="height: 250px; width: 100%;"
    data-marker="<%= @marker.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
  <div class="reservations m-3 mt-4">
    <h5 class="reservation mr-1">Reservation start: <strong><%= @start_time %></strong></h5>
    <h5 class="reservation ml-1">Reservation end: <strong><%= @end_time %></strong></h5>
  </div>
  <h3 class="price">TOTAL: <strong><%= @result %>€</strong></h3>
  <%= hidden_field_tag 'renting_time', @result / @car.price_per_hour %>
  <%= f.submit "Book", class: "custom-button w-50 mt-4 mb-3", data: { confirm: "Are you sure?" }%>
  <% end %>
</div>

app/views/cars/_form.html.erb
<div class="container mt-4 mb-4">
  <div class="text-center">
    <h2>Enter Car Details</h2>
  </div>
    <%= simple_form_for (@car) do |f| %>
    <div class="box-w mt-3">
      <div class="form-inputs">
        <%= f.input :brand, placeholder: "BMW"%>
        <%= f.input :car_model, placeholder: "7 Series"%>
        <%= f.input :year, placeholder: "2018"%>
        <%= f.input :milage, label: "Mileage", placeholder: "30000" %>
        <%= f.input :seats, placeholder: "4" %>
        <%= f.input :combustion, placeholder: "Diesel" %>
        <%= f.input :transmission, placeholder: "Automatic" %>
        <%= f.input :accessories, placeholder: "Air Conditonning, Anti Lock Braking System, Voice Control..." %>
        <%= f.input :plate_number, placeholder: "3650GYG" %>
        <%= f.input :price_per_hour, label: "Price Per Hour (€)", placeholder: "200" %>
        <%= f.input :description, placeholder: "Description..." %>
        <%= f.input :location, placeholder: "Your location" %>
        <%= f.input :photo, placeholder: "URL of photo" %>
      </div>
    <div class="submit text-center">
      <%= f.button :submit, class: "custom-button padding-right-left"%>
    <% end %>
    </div>
    <div class="text-center mt-3">
      <%= link_to "Go Back", cars_path, class: "custom-button" %>
    </div>
  </div>
</div>

app/views/cars/_info_window.html.erb
<%= link_to car_path(car) do %>
      <div class="info-img p-0" style="background-image: url('<%= image_path car.photo %>')"></div>
  <div class="text-center txt">
    <h5 class="m-0"><%= car.brand.upcase %></h5>
    <p class="m-0"><strong><%= car.car_model.upcase %></strong></p>
    <div class="price">
      <p class="m-0"><%= car.price_per_hour %>€ / H</p>
    </div>
  </div>
<% end %>

app/views/cars/edit.html.erb
<%= render "form" %>

app/views/cars/index.html.erb
<div class="text-center p-5">
  <h1>TIME TO PICK A CAR!</h1>
</div>
<div class="conta d-flex align-items-start">
  <div class="d-flex flex-colum align-items-center justify-content-center" style="width: 100%">
  <div class="cards ml-1">
  <% @cars.each do |car| %>
    <div class="card">
      <%= link_to car_path(car) do %>
      <div class="card-img-top rounded pho" width="100%" style="background-image: url('<%= image_path car.photo %>')"></div>
      <% end %>
    <div class="card-body" >
    <h5 class="m-0"><%= car.brand %> - <%= car.car_model %></h5>
    <% suma = 0 %>
    <% media = 0 %>
    <% car.reviews.each { |rev| suma += rev.rating } %>
    <% car.reviews.length.zero? ?  media = 0 : media = (suma / car.reviews.length).round %>
    <% media.times do %>
     <i class="fas fa-star" style="color: #6FCFE1;"></i>
     <% end %>
     <% (5 - media).times do %>
     <i class="fas fa-star" style="color: rgb(220,220,220);"></i>
     <% end %>
     <%= car.reviews.length %> reviews
      <img src='<%= car.user.photo %>' class="avatar-bordered card-avatar">
    </div>
    <div class="box p-2">
    <h4><%= car.price_per_hour%>€</h4>
    <span>PER HOUR</span>
    </div>
    </div>
  <% end %>
  </div>
</div>
<div
  id="map"
  class="mapbox indexmap"
  style="width: 50%;
  height: 100vh; margin-top: 10px; padding: 0 15px; margin-left: 5px; position: sticky; top: 3%;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
</div>

app/views/cars/new.html.erb
<%= render 'form' %>

app/views/cars/show.html.erb
  <div class="main-container">
  <div class="top-info d-flex w-100">
    <div class="picture" id="car_picture" style="background-image: url('<%= image_path @car.photo %>')"></div>
      <div
    id="map"
    class="showmap"
    style="width: 100%;
    height: 400px; margin-right: 20px; margin-top: 20px; margin-left: 10px; border-radius: 5px;"
    data-marker="<%= @marker.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>


  <div class="info-car">
      <div class="infos ml-2">
        <h1><%= @car.brand %> - <%= @car.car_model %>  <% if policy(@car).edit? %><%= link_to raw('<i class="fas fa-trash"></i>'), car_path(@car), method: :delete, data: { confirm: "Are you sure?" } %><% end %></h1>
        <p><%= @car.year %> |  <%= @car.seats %> seats <% if policy(@car).edit? %><%= link_to "Edit", edit_car_path(@car)%><% end %></p>
        <% @lamediabook.times do %>
         <i class="fas fa-star" style="color: #6FCFE1;"></i>
        <% end %>
        <% (5 - @lamediabook).times do %>
         <i class="fas fa-star" style="color: rgb(220, 220, 220);"></i>
         <% end %>
         <%= @numreviewbook %> reviews
        </div>
      </div>
    </div>
    </div>
<div class="d-flex justify-content-between the-container">
  <div class="show-cards">
    <div class="show-card">
      <h5><strong>OWNER</strong></h5>
      <div class="d-flex align-items-end">
        <img src="<%= @car.user.photo %>" alt="" class="avatar cust">
        <div class="ml-3 reviews d-flex align-items-end">
          <div class="stars">
          <p><%= @car.user.full_name %></p>
          <% @lamediauser.times do %>
            <i class="fas fa-star" style="color: #6FCFE1;"></i>
          <% end %>
          <% (5 - @lamediauser).times do %>
            <i class="fas fa-star" style="color: rgb(220, 220, 220);"></i>
          <% end %>
         <span class="ml-1">  <%= @numreviewuser %> reviews</span>
           </div>
          </div>
       </div>
    </div>

      <% if @car.description.nil?%>
      <%=  %>
      <% else %>
    <div class="show-card">
      <h5><strong>CAR DESCRIPTION</strong></h5>
      <p><%= @car.description %></p>
    </div>
      <% end %>

      <% unless @car.owner_conditions.nil? %>
      <div class="show-card">
        <h5><strong>OWNER CONDITIONS</strong></h5>
        <p><%= @car.owner_conditions %></p>
      </div>
      <% end %>

      <div class="show-card">
        <h5 class="mb-4"><strong>TECHNICAL CHARACTERISTICS</strong></h5>
        <p><i class="fas fa-gas-pump mr-1" style="color: #D4AF37; font-size: 20px;"></i><strong>Combustion</strong>: <%= @car.combustion %>      -    <strong>Transmission</strong>: <%= @car.transmission %></p>
        <p class="m-0"><i class="fas fa-tachometer-alt mr-1" style="color: #D4AF37; font-size: 20px;"></i><strong>Milage</strong>: <%= @car.milage %>km</p>
      </div>

      <% if @car.accessories.nil?%>
      <%=  %>
      <% else %>
        <div class="show-card">
          <h5><strong>OPTIONS AND ACCESORIES</strong></h5>
          <p><%= @car.accessories %></p>
        </div>
      <% end %>
    <div class="show-card rev">
      <h4 class="mb-4"><strong>REVIEWS</strong></h4>
      <% @bookings.each do |book| %>
        <% unless book.review == nil %>
        <div class="d-flex justify-content-start align-items-center border-bottom pb-4 mt-3">
          <img src="<%= book.user.photo %>" alt="" class="avatar cust m-0 mr-3">
          <div class="user">
            <h5><%= book.user.full_name %> </h5>
            <% book.review.rating.times do %>
              <i class="fas fa-star" style="color: #6FCFE1;"></i>
            <% end %>
             <% (5 - book.review.rating).times do %>
              <i class="fas fa-star" style="color: rgb(220, 220, 220);"></i>
            <% end %>
            <p class="m-0"><%= book.review.content %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <% if !policy(@car).edit? %>
      <div class="new-box">
        <h5 class="mb-2">Dates</h5>
        <%= simple_form_for :booking, url: car_send_booking_path(@car.id), method: "post" do |f| %>
          <%= f.input :starts_at, as: :string, required: true, input_html: {class: "datepicker"} %>
          <%= f.input :ends_at, as: :string, required: true, input_html: {class: "datepicker"} %>
        <div class="tex">
          <h1 id="final_price"></h1>
          <p>Price per hour: <span id="car_price"><%= @car.price_per_hour %>€</span></p>
        </div>
        <%= f.button :submit, "Book It", class:"custom-button w-75 mb-3", style:"position: absolute; left: 12%; bottom: 0%" %>
        <% end %>
      </div>
    <% end %>
</div>
<!--      -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Luxury Car Rental</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body id="<%= params[:controller] %>/<%= params[:action] %>">
    <%= render 'shared/navbar' %>
    <div class="c2">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1 class="text-center pt-4 pb-2">MY CARS</h1>
<div class="conta d-flex">
<div class="home-cards ml-1">
<% @cars.each do |car| %>
  <div class="home-card">
    <%= link_to car_path(car) do %>
    <div class="home-card-img-top rounded home-pho" width="100%" style="background-image: url('<%= image_path car.photo %>')"></div>
    <% end %>
  <div class="home-card-body" >
  <h5 class="m-0"><%= car.brand %> - <%= car.car_model %></h5>
  <% mycarbookings = Booking.all.select { |book| book.car_id == car.id } %>
  <% sumacarbook = 0 %>
  <% mediacarbook = 0 %>
  <% numreviewcarbook = 0 %>
  <% mycarbookings.each { |boook| sumacarbook += boook.review.rating if boook.review } %>
  <% mycarbookings.each { |boook| numreviewcarbook += 1 if boook.review } %>
  <% numreviewcarbook.zero? ?  mediacarbook = 0 : mediacarbook = (sumacarbook / numreviewcarbook).round %>
  <p class="home-card-text m-0">
  <% mediacarbook.times do %>
   <i class="fas fa-star" style="color: #6FCFE1;"></i>
   <% end %>
      <% (5 - mediacarbook).times do  %>
        <i class="fas fa-star" style="color: rgb(220,220,220)"></i>
      <% end %><%= numreviewcarbook %> reviews</p>
    <img src='<%= car.user.photo %>' class="avatar-bordered home-card-avatar">
  </div>
  <div class="home-box p-2">
  <h4><%= car.price_per_hour%>€</h4>
  <span>PER HOUR</span>
  </div>
  </div>
<% end %>
</div>
</div>
<% if @rentals.length > 0 %>
<h1 class="text-center pt-4 pb-2">My Rentals</h1>
<div class="conta d-flex">
<div class="home-cards ml-1">
<% @rentals.each do |book| %>
  <div class="home-card">
    <%= link_to car_path(book.car) do %>
    <div class="home-card-img-top rounded home-pho" width="100%" style="background-image: url('<%= image_path book.car.photo %>')"></div>
    <% end %>
  <div class="home-card-body" >
  <h5 class="m-0"><%= book.car.brand %> - <%= book.car.car_model %></h5>
  <% carbookings = Booking.all.select { |boook| boook.car_id == book.car_id } %>
  <% sumabook = 0 %>
  <% mediabook = 0 %>
  <% numreview = 0 %>
  <% carbookings.each { |boook| sumabook += boook.review.rating if boook.review } %>
  <% carbookings.each { |boook| numreview += 1 if boook.review } %>
  <% numreview.zero? ?  mediabook = 0 : mediabook = (sumabook / numreview).round %>
  <% mediabook.times do %>
   <i class="fas fa-star" style="color: #6FCFE1;"></i>
   <%  end %>
   <% (5 - mediabook).times do %>
   <i class="fas fa-star" style="color: rgb(220,220,220);"></i>
   <%  end %>
   <%= numreview %> reviews
    <img src='<%= book.car.user.photo %>' class="avatar-bordered home-card-avatar">
  </div>
  <div class="home-box p-2">
  <h4><%= book.car.price_per_hour%>€</h4>
  <span>PER HOUR</span>
  </div>
   <div class="review-link"><%= link_to "Leave a review",  new_booking_review_path(book.id)%></div>
  </div>
<% end %>
<% end %>
</div>
</div>

app/views/pages/home.html.erb
<div class="cont" style="background-image: url(<%= asset_path 'Home2.jpg' %>);">
    <div class="d-flex flex-column align-items-center justify-content-center banner-header">
      <h1>Rent a <strong>Luxury Car</strong></h1>

      <div class="search-bar">
        <%= form_tag cars_path, method: :get do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control custom",
            placeholder: "Brand/Model/Transmission/Year"
         %>
        <%= submit_tag "BROWSE", class: "custom-button" %>
        <% end %>
      </div>
    </div>
  <svg class="pulse" viewBox="0 0 1024 1024" version="1.1">
        <circle id="Oval" cx="512" cy="512" r="512"></circle>
        <circle id="Oval" cx="512" cy="512" r="512"></circle>
        <circle id="Oval" cx="512" cy="512" r="512"></circle>
    </svg>
</div>

<div class="home-cont">
    <h2><strong>FEATURED CARS</strong></h2>
</div>

<div class="home-cards">
<% @cars.first(3).each do |car| %>
  <div class="home-card">
    <%= link_to car_path(car) do %>
    <div class="home-card-img-top rounded home-pho" width="100%" style="background-image: url('<%= image_path car.photo %>')"></div>
    <% end %>
  <div class="home-card-body" >
  <h5 class="m-0"><%= car.brand %> - <%= car.car_model %></h5>
  <% suma = 0 %>
  <% media = 0 %>
  <% car.reviews.each { |rev| suma += rev.rating } %>
  <% car.reviews.length.zero? ?  media = 0 : media = (suma / car.reviews.length).round %>
  <% media.times do %>
   <i class="fas fa-star" style="color: #6FCFE1;"></i>
   <% end %>
   <% (5 - media).times do %>
   <i class="fas fa-star" style="color: rgb(220,220,220);"></i>
   <% end %>
   <%= car.reviews.length %> reviews
    <img src='<%= car.user.photo %>' class="avatar-bordered home-card-avatar">
  </div>
  <div class="home-box p-2">
  <h4><%= car.price_per_hour%>€</h4>
  <span>PER HOUR</span>
  </div>
  </div>
<% end %>
</div>

app/views/reviews/create.html.erb
  <%= link_to "Add a review", new_booking_review_path, class: "custom-button" %>

app/views/reviews/new.html.erb
<div class="container hst mt-5 mb-5" style="min-height: 60vh;">
<%= simple_form_for [@booking, @review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :content %>
  <div class="text-center pt-4">
  <%= f.submit "Send", class: "custom-button"%>
  </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
  <nav class="fill navbar">
      <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "http://mrluxuryconnect.com/wp-content/uploads/2016/01/Gold-And-Black-300x169.png" %>
    <% end %>
    <ul>
        <div class="search-bar-nav">
      <%= form_tag cars_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
          params[:query],
          class: "form-control custom",
          placeholder: "Search for a car"
       %>
       <%= button_tag(type: 'submit', class: "custom-button w-25") do %>
          <i class="fas fa-search"></i>
        <% end %>
      <% end %>
  </div>
    <% if user_signed_in? %>
      <li class="signedin"><%= link_to "Dashboard", dashboard_path %></li>
      <li class="signedin"><%= link_to "Cars", cars_path %></li>
      <li class="signedin"><%= link_to "Rent Your Car", new_car_path %></li>
      <% if current_user.photo.present? %>
      <li><%= image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item text-center" %>
            <%= link_to "Rent Your Car", new_car_path, class: "dropdown-item text-center" %>
            <%= link_to "Cars", cars_path, class: "dropdown-item text-center" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item text-center" %>
          </div>
      </li>
      <% else %>
      <li><%= image_tag "https://i.pravatar.cc/300", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item text-center" %>
          </div>
      </li>

      <% end %>
    <% else %>
      <li class="ml-2"><%= link_to "Login", new_user_session_path %></li>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <% end %>
    </ul>
  </nav>